// <auto-generated />
using System;
using HysteriaAuth.Master.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HysteriaAuth.Master.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524120810_ExpandNodeTable")]
    partial class ExpandNodeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.Admin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.AdminAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("AdminAuditLogs", (string)null);
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.AuthLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AuthTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuthLogs", (string)null);
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BandwidthDown")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("BandwidthUp")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCycle")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("BrutalTxBandwidth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfigUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CongestionControl")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnablePortHopping")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EnableSpeedTest")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IgnoreClientBandwidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MasqueradeFile")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MasqueradeProxyUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MasqueradeReplyBps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasqueradeStringContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasqueradeStringHeaders")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MasqueradeStringStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasqueradeType")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObfsPassword")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObfsType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortHopRangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortHopRangeStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProvisionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("QuicInitConnectionReceiveWindow")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QuicInitStreamReceiveWindow")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QuicMaxConnectionReceiveWindow")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuicMaxIdleTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QuicMaxStreamReceiveWindow")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuicMaxUdpPayloadSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolverResolveConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolverResolveInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolverTcpAddr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolverTlsAddr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolverType")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolverUdpAddr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SecretVersion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ServerCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("SniffEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SniffRespectHttps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SniffTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SpeedTestDownloadSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpeedTestPingInterval")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SpeedTestUploadSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrafficStatsPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrafficStatsSecret")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UdpIdleTimeout")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProvisionToken")
                        .IsUnique();

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.NodeStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveConnections")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<float>("MemoryTotalMb")
                        .HasColumnType("REAL");

                    b.Property<float>("MemoryUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<float>("MemoryUsedMb")
                        .HasColumnType("REAL");

                    b.Property<long>("NetworkInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<float>("NetworkInMbps")
                        .HasColumnType("REAL");

                    b.Property<long>("NetworkOutBytes")
                        .HasColumnType("INTEGER");

                    b.Property<float>("NetworkOutMbps")
                        .HasColumnType("REAL");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("NodeStatuses", (string)null);
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.NodeTraffic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalBytesIn")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytesOut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("NodeTraffics", (string)null);
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesIn")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesOut")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.TrafficRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesIn")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesOut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("TrafficRecords", (string)null);
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedNodes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<long>("TotalTrafficBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UsedTrafficBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.AdminAuditLog", b =>
                {
                    b.HasOne("HysteriaAuth.Master.Models.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.AuthLog", b =>
                {
                    b.HasOne("HysteriaAuth.Master.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.NodeStatus", b =>
                {
                    b.HasOne("HysteriaAuth.Master.Models.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.NodeTraffic", b =>
                {
                    b.HasOne("HysteriaAuth.Master.Models.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.Session", b =>
                {
                    b.HasOne("HysteriaAuth.Master.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HysteriaAuth.Master.Models.Entities.TrafficRecord", b =>
                {
                    b.HasOne("HysteriaAuth.Master.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
